In [ ]:
a1=[1,2,3]
a2=[4,5,6]
sum_r
for i in r

(5, 7, 9)


In [ ]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([1])
print(np.add(a1,a2))

[2 3 4]


In [ ]:
#Problem1
#Task1
import numpy as np
array=np.zeros((2,2))
print(array)

[[0. 0.]
 [0. 0.]]


In [ ]:
#Task2
import numpy as np
array=np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Task3
import numpy as np
array=np.full((3,5),6)
print(array)


[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [1]:
#Qn4
import numpy as np
#Example array
array = np.array([[2, 2], [3, 3]])

#New array of zeros with same shape and size as example array
zeroArray = np.zeros_like(array)
print(zeroArray)

[[0 0]
 [0 0]]


In [2]:
#Qn5
import numpy as np
#Example array
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#New array of ones with same shape and size as example array
onesArray = np.ones_like(arr1)
print(onesArray)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
#Qn6
import numpy as np

new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [4]:
#Problem2
#Qn1
import numpy as np

#use of arange allows to print from 10 to 49 and doesnot include 50
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Qno2
import numpy as np
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Qno3
import numpy as np
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#Qno4
import numpy as np
arr = np.random.random(30)
mean = arr.mean()
print(arr, mean)

[0.99380084 0.8728134  0.26371868 0.75670471 0.79914149 0.64997157
 0.06344203 0.26850513 0.56224166 0.33798877 0.42917192 0.44340184
 0.30671832 0.81790419 0.56175659 0.91707546 0.63296952 0.05407543
 0.31998387 0.74036202 0.78120775 0.46547312 0.95992331 0.71346976
 0.90877914 0.63095813 0.34917692 0.7843133  0.16353752 0.9380118 ] 0.5828866066305513


In [8]:
#Qno5
import numpy as np
arr = np.random.random((10, 10))
arr_min = arr.min()
arr_max = arr.max()
print("Minimum Value:", arr_min, "\nMaximum Value:", arr_max)

Minimum Value: 0.009592174189860914 
Maximum Value: 0.9805012834299668


In [9]:
#Qno6
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#Qno7
import numpy as np
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.array(arr)[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [11]:
#Qno8
import numpy as np
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
#Qno9
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [13]:
#Problem-3:Array Operations
#Qno1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_arr = x + y
add_arr1 = v + w
print("Addition of X and Y:", add_arr, "\nAddition of V and W:", add_arr1)

Addition of X and Y: [[ 6  8]
 [10 13]] 
Addition of V and W: [20 22]


In [15]:
#Qno2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sub_arr = x - y
sub_arr1 = v - w
print("Subtraction of X and Y:", sub_arr, "\nSubtraction of V and W:", sub_arr)

Subtraction of X and Y: [[-4 -4]
 [-4 -3]] 
Subtraction of V and W: [[-4 -4]
 [-4 -3]]


In [16]:
#Qno3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
mult_arr = x * 9
print(mult_arr)

[[ 9 18]
 [27 45]]


In [17]:
#Qno4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square_arrX = x**2
square_arrY = y**2
square_arrV = v**2
square_arrW = w**2
print(square_arrX, "\n",square_arrY, "\n",square_arrV,"\n" ,square_arrW)

[[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]] 
 [ 81 100] 
 [121 144]


In [18]:
#Qno5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)
print("Dot Product of V and W:",dot_product_vw, "\nDot Product of X and V: ",dot_product_xv,"\nDot Product of X and Y:",dot_product_xy)

Dot Product of V and W: 219 
Dot Product of X and V:  [29 77] 
Dot Product of X and Y: [[19 22]
 [50 58]]


In [19]:
#Qno6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.vstack((v, w)).T
print(concat_xy_rows)
print(concat_vw_columns)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [20]:
#Qno7
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print(concat_xv_error)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [21]:
#Problem-4: Matrix Operations
#Qno1
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print(identity)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [22]:
#Qno2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
AB_not_equal_BA = not np.array_equal(AB, BA)